/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import entidades.Alumno;
import entidades.Materia;
import javax.swing.JOptionPane;
import tp4_obligatorio.Colegio;

/**
 *
 * @author Moon
 */
public class GuiInscribirAlumno extends javax.swing.JFrame {

    /**
     * Creates new form GuiInscribirAlumno
     */
    public GuiInscribirAlumno() {
        initComponents();
         setResizable(false);
                       
        for (Alumno alumno : Colegio.getAlumnos()) {
            
            jBoxAlumno.addItem(alumno);
        }
        
        for (Materia materia : Colegio.getMaterias()) {
            jBoxMateria.addItem(materia);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        BG = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBoxAlumno = new javax.swing.JComboBox<>();
        jBoxMateria = new javax.swing.JComboBox<>();
        jLMateria = new javax.swing.JLabel();
        jLAlumno = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(596, 443));
        setResizable(false);
        setSize(new java.awt.Dimension(596, 443));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver.setBackground(new java.awt.Color(53, 44, 91));
        jButtonVolver.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.setBorder(null);
        jButtonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        BG.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 100, 30));

        jBtnGuardar.setBackground(new java.awt.Color(53, 44, 91));
        jBtnGuardar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setBorder(null);
        jBtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        BG.add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 100, 30));

        jBoxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxAlumnoActionPerformed(evt);
            }
        });
        BG.add(jBoxAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 200, -1));

        jBoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxMateriaActionPerformed(evt);
            }
        });
        BG.add(jBoxMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 200, -1));

        jLMateria.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLMateria.setForeground(new java.awt.Color(51, 51, 51));
        jLMateria.setText("Materia");
        BG.add(jLMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLAlumno.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLAlumno.setForeground(new java.awt.Color(51, 51, 51));
        jLAlumno.setText("Alumno");
        BG.add(jLAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        sidePanel.setBackground(new java.awt.Color(53, 44, 91));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inscribir Alumno");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        sidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 10));

        BG.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBoxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxAlumnoActionPerformed
        
    }//GEN-LAST:event_jBoxAlumnoActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        GuiMain main = new GuiMain();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        int aux = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea guardar los cambios?");
        if (aux == 0) {
            for (Alumno alumno : Colegio.getAlumnos()) {
                if (jBoxAlumno.getSelectedItem() == alumno) {
                     if (alumno.agregarMateria((Materia) jBoxMateria.getSelectedItem())) {
                        JOptionPane.showMessageDialog(rootPane, "Inscripción realizada correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "El alumno ya está inscripto en esta materia.");
                    }
                }
            }            
        } else if (aux == 1) {
            
        }    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxMateriaActionPerformed

    }//GEN-LAST:event_jBoxMateriaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JComboBox<Object> jBoxAlumno;
    private javax.swing.JComboBox<Object> jBoxMateria;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLAlumno;
    private javax.swing.JLabel jLMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
