/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import entidades.Alumno;
import entidades.Materia;
import java.util.Arrays;
import static java.util.Collections.list;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import tp4_obligatorio.Colegio;

/**
 *
 * @author Moon
 */
public class GuiInscribirAlumno extends javax.swing.JFrame {

    /**
     * Creates new form GuiInscribirAlumno
     */
    public GuiInscribirAlumno() {
        initComponents();
         setResizable(false);
                       
        for (Alumno alumno : Colegio.getAlumnos()) {
            
            jBoxAlumno.addItem(alumno);
        }
        
        for (Materia materia : Colegio.getMaterias()) {
            jBoxMateria.addItem(materia);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jTitulo = new javax.swing.JLabel();
        jLAlumno = new javax.swing.JLabel();
        jLMateria = new javax.swing.JLabel();
        jBoxMateria = new javax.swing.JComboBox<>();
        jBoxAlumno = new javax.swing.JComboBox<>();
        jButtonVolver = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTitulo.setText("Inscribir Alumno");

        jLAlumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLAlumno.setText("Alumno");

        jLMateria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLMateria.setText("Materia");

        jBoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxMateriaActionPerformed(evt);
            }
        });

        jBoxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxAlumnoActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLMateria)
                    .addComponent(jLAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTitulo)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTitulo)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAlumno)
                    .addComponent(jBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMateria)
                    .addComponent(jBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBoxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxAlumnoActionPerformed
        //?????????
    }//GEN-LAST:event_jBoxAlumnoActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        GuiMain main = new GuiMain();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        int aux = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea guardar los cambios?");
        if (aux == 0) {
            for (Alumno alumno : Colegio.getAlumnos()) {
                if (jBoxAlumno.getSelectedItem() == alumno) {
                    alumno.agregarMateria((Materia)jBoxMateria.getSelectedItem());
                }
            }
            JOptionPane.showMessageDialog(rootPane, "Inscripción realizada correctamente");
            jBtnGuardar.setEnabled(false);
        } else if (aux == 1) {
            jBtnGuardar.setEnabled(false);
        }    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxMateriaActionPerformed

    }//GEN-LAST:event_jBoxMateriaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> jBoxAlumno;
    private javax.swing.JComboBox<Object> jBoxMateria;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLAlumno;
    private javax.swing.JLabel jLMateria;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
